-- CAB GCU Storage Room — seed data (the original 199-item inventory).
-- Run after schema.sql, once, to populate the items table.

insert into public.items (id, name, cat, unit, shelf, team, notes, contents, emoji, out, flag, log) values
('CAB-0001', 'Christmas trees', 0, 'A', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0002', 'Christmas street corner lights (x2)', 0, 'A', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0003', 'Box of christmas ornaments', 0, 'A', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0004', 'Christmas lights', 0, 'A', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0005', 'Fake Christmas Decorations', 0, 'A', 3, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0006', 'Inflatable igloo', 0, 'A', 1, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0007', 'Wreath Lights', 0, 'A', 2, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0008', 'Large ornaments', 0, 'A', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0009', 'Christmas garlands', 0, 'A', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0010', 'Box of CHRISTMAS lights', 0, 'A', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0011', 'Jumbo Christmas Ornaments (3)', 0, 'A', 3, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0012', 'Sleds (21)', 0, 'A', 3, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0013', 'Santa suits', 0, 'A', 3, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0014', 'Christmas decor box', 0, 'A', 3, '', '', 'Wreath, table & wall decor & some DIY ornaments', '', NULL, NULL, '[]'::jsonb),
('CAB-0015', 'Lighgt up christmas presents', 0, 'A', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0016', '5 boxes of tree tinsil', 0, 'A', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0017', 'christmas blankets and pillows', 0, 'A', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0018', 'Christmas inflatables', 0, 'A', 1, 'ALL', 'jus', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0019', 'Christma Tree', 0, 'A', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0020', 'Chistmas snow', 0, 'A', 1, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0021', 'Random christmas decor', 0, 'A', 3, 'Pastimes', '', 'Cab stockings, red bows, christmas plant table decor', '', NULL, NULL, '[]'::jsonb),
('CAB-0022', 'Flowers and pink bows', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0023', 'vines and fake flowers', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0024', '2 boxes of fake flowers', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0025', 'Flower Centerpieces', 3, 'A', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0026', 'Green Vines', 3, 'A', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0027', 'Fake flowers', 3, 'A', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0028', 'Flowers', 3, 'A', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0029', 'Easter Eggs', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0030', 'Flowers (assorted)', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0031', 'Easter grass', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0032', 'succulents decor', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0033', 'egg dye kits', 3, 'A', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0034', 'Easter decor', 3, 'A', 4, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0035', 'Flowers', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0036', 'Greenary', 3, 'A', 4, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0037', 'Pink bows Cupid Shuffle', 3, 'A', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0038', 'grass skirts', 4, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0039', 'Inflatables/ rubber duckies', 4, 'A', 5, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0040', 'Tropical Bin (palm tree, flamingo light)', 4, 'A', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0041', 'Tropical decor', 4, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0042', 'floaties/water guns', 4, 'A', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0043', 'Water floats', 4, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0044', 'Water Guns', 4, 'A', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0045', 'Ducks', 4, 'A', 5, 'Marketing', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0046', 'Country Lopes Decor (Coastal/USA)', 5, 'A', 5, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0047', 'USA Country lopes Decor', 5, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0048', 'Box of space cowboy decor', 5, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0049', 'USA flag', 5, 'A', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0050', 'Haunted House Tarp', 1, 'B', 1, 'Nightlife', '*Who checked it out/ when?', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0051', 'Haunted House Costumes', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0052', 'Haunted House Masks', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0053', 'Black inflatable cat', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0054', 'Haunted House Body Parts', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0055', 'Haunted House Lighting', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0056', 'Haunted House Gravestons/Weapons/Props', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0057', 'Haunted House Dead Body', 1, 'B', 1, 'Nightlife', 'In a black garbage bag', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0058', 'Clown Archway Inflatable', 1, 'B', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0059', 'Haunted House Dolls', 1, 'B', 1, 'Nightlife', 'Random', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0060', 'Fake blood, fog machine, ropes', 1, 'B', 2, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0061', 'chicken wire/barbed wire', 1, 'B', 2, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0062', 'Spiders', 1, 'B', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0063', 'Bloody Sheets', 1, 'B', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0064', 'Black Cloths', 1, 'B', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0065', 'Scarecrows', 1, 'B', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0066', 'pitchfork', 1, 'B', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0067', 'haunted house banner', 1, 'B', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0068', 'Fall trees', 2, 'B', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0069', 'Pumpkins', 2, 'B', 3, 'Nightlife', '', 'Pumpkins, decorations ect.', '', NULL, NULL, '[]'::jsonb),
('CAB-0070', 'Fall Leaves', 2, 'B', 3, 'Special Events', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0071', 'Random Fall Decor', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0072', 'Box of fake hay', 2, 'B', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0073', 'pumpkin baskets', 2, 'B', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0074', 'Fall Leaves', 2, 'B', 3, 'Special Events', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0075', 'Candles (6), Pumpkins (Small 13, Large 10)', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0076', 'Fall Decor (limbo, turkey bowling pins)', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0077', 'Leaf lanyards', 2, 'B', 3, 'Special Events', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0078', 'Box of fall leaves', 2, 'B', 3, 'Special Events', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0079', 'Fall stuff', 2, 'B', 3, '', 'Leaves and misc. decor', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0080', 'Fall leaves', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0081', 'Pumpkins', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0082', 'Candles & pumpkins', 2, 'B', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0083', 'Inflatable Nerf', 8, 'B', 4, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0084', 'Golf set (chip & stick)', 8, 'B', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0085', 'Box of duck hunt stuff', 8, 'B', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0086', 'Nerf pennies and circle nerf bullets (boxes)', 8, 'B', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0087', 'Nerf guns (old)', 8, 'B', 4, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0088', 'rubber ducks', 8, 'B', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0089', 'Square table vases', 8, 'B', 5, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0090', 'Spikeball', 8, 'B', 5, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0091', 'Bingo supplies', 8, 'B', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0092', 'Cornhole boards and field games', 8, 'B', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0093', '9 square', 8, 'B', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0094', 'nerf guns (new)', 8, 'B', 4, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0095', 'Giant connect 4', 8, 'B', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0096', 'Nerf bullet picker upper', 8, 'B', 4, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0097', 'Bowling supplies', 8, 'B', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0098', 'Cablympics supplies', 8, 'B', 5, 'ALL', '', 'fuzzy balls, plastic buckets, cups, ping pong balls, balloons and nerf bullets', '', NULL, NULL, '[]'::jsonb),
('CAB-0099', 'Jenga', 8, 'B', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0100', 'Nerf Wars Black Pool Noodles', 8, 'B', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0101', 'Neon Glow Party', 6, 'C', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0102', 'Back to school decorations/neon stuff', 6, 'C', 1, 'ALL', 'Neon with back to school decorations', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0103', 'Box of galaxy projector lights/ lava lamps', 6, 'C', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0104', 'box of string & fairie lights', 6, 'C', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0105', 'fairy lights and glittery backdrops', 6, 'C', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0106', 'Disco Balls (small)', 6, 'C', 1, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0107', 'Disco balls/lights', 6, 'C', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0108', 'Way Back Wednesday glow sticks/decor', 6, 'C', 1, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0109', 'circus banners', 7, 'C', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0110', 'Ball pit balls', 7, 'C', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0111', 'Circus toss games', 7, 'C', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0112', 'Circus toss games', 7, 'C', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0113', 'Fair Items', 7, 'C', 2, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0114', 'red carpets', 12, 'C', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0115', 'Canapy tents', 12, 'C', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0116', 'Triangular Arch Backdrop', 12, 'C', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0117', 'Black inflatable arch', 12, 'C', 2, 'Nightlife', 'Also student markets!', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0118', 'Conductor Stand', 12, 'C', 2, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0119', 'Greenery Wall', 12, 'C', 3, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0120', 'camel crown tent', 12, 'C', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0121', 'Tablecloths/ Table Runners (blue)', 12, 'C', 3, 'Marketing', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0122', 'Sparkly Drapes', 12, 'C', 3, 'Special Events', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0123', 'Conducter stands', 12, 'C', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0124', 'Tablecloths', 12, 'C', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0125', 'Table paper holders', 12, 'C', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0126', 'Drapes', 12, 'C', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0127', 'Paper holder stands', 12, 'C', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0128', 'portable backdrops', 12, 'C', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0129', 'Table stands', 12, 'C', 3, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0130', 'Tablecloths,', 12, 'C', 3, 'ALL', 'black blue', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0131', 'Turf', 12, 'C', 3, 'ALL', 'Rolls of turf', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0132', 'Paintings (x10)', 14, 'C', 4, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0133', 'Reflective Paper (3)', 14, 'C', 4, 'Misc.', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0134', 'foam rollers', 14, 'C', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0135', 'beads', 14, 'C', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0136', 'paint trays 2x', 14, 'C', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0137', 'Canas, Close Pins, Watercolor Cards', 14, 'C', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0138', 'Paint supplies', 14, 'C', 4, 'Arts', 'Paint holders strips', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0139', 'Records', 14, 'C', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0140', 'brown kraft paper', 14, 'C', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0141', 'Paint supplies', 14, 'C', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0142', 'white totes', 14, 'C', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0143', 'Glass Vases', 16, 'C', 5, 'Arts', 'also some in A4', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0144', 'Candle Fixtures', 16, 'C', 5, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0145', '2 boxes of large vases', 16, 'C', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0146', 'Box of empty lanterns', 16, 'C', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0147', 'glass vases', 16, 'C', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0148', 'Wooden decorative baskets', 16, 'C', 5, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0149', 'Box of mason jars & coke bottles', 16, 'C', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0150', 'Mason Jars', 16, 'C', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0151', 'Large bulb string lights', 10, 'D', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0152', 'Mini bulb lights (10 strands', 10, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0153', 'LED floor decorative lights', 10, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0154', '1 single light bulb', 10, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0155', 'wooden hanging sign', 10, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0156', 'Light bulbs', 10, 'D', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0157', 'miscellaneous battery candles and lights', 10, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0158', 'Spotlight for lopes live', 11, 'D', 1, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0159', 'Tripods', 11, 'D', 1, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0160', 'Food stuff', 13, 'D', 2, 'ALL', '', 'Syran wrap, bowls, etc.', '', NULL, NULL, '[]'::jsonb),
('CAB-0161', 'aprons', 13, 'D', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0162', 'Empty Water Toph', 13, 'D', 2, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0163', 'Skewers (marshmrellow)', 13, 'D', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0164', 'Chef hats', 13, 'D', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0165', 'Cooler', 13, 'D', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0166', 'Breakfast skillet', 13, 'D', 2, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0167', 'Igloo cooler', 13, 'D', 2, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0168', 'Cooler', 13, 'D', 2, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0169', 'Totes', 15, 'D', 3, 'Markets', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0170', 'Totes', 15, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0171', 'camping chair', 15, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0172', 'Buckets/baskets', 15, 'D', 3, '', 'Halloween buckets', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0173', 'disney masks/ears', 18, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0174', 'Lightsabers', 18, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0175', 'wigs', 18, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0176', 'inflatable costumes', 18, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0177', 'Chewbaca costume', 18, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0178', 'Blow Up Suits', 18, 'D', 3, 'Marketing', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0179', 'Casino night flag', 19, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0180', 'yellow brick road runner', 19, 'D', 3, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0181', 'rainbow balls', 20, 'D', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0182', 'heart balloons', 20, 'D', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0183', 'Bubble solution', 20, 'D', 4, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0184', 'Light up wristbands', 20, 'D', 4, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0185', 'Bubble machine', 20, 'D', 4, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0186', 'Bubble machine & string lights', 20, 'D', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0187', 'neon student engagement sign', 21, 'D', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0188', 'Grow With Wherever Life Plants You', 21, 'D', 4, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0189', 'Wooden crates/ wooden signs', 21, 'D', 4, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0190', 'Air Matresses Pumps', 22, 'D', 5, 'Nightlife', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0191', 'Duct tape box', 22, 'D', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0192', '5 gallon buckets and paint rollers', 22, 'D', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0193', 'Heater', 22, 'D', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0194', 'Blankets', 25, 'D', 5, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0195', 'Stantions', 25, 'D', 5, 'ALL', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0196', 'Sheets', 25, 'D', 5, 'Nightlife', 'Make it easier for us to track down items if things go missing or another team needs something.', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0197', 'ties', 25, 'D', 5, '', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0198', 'Blankets', 25, 'D', 5, 'Arts', '', '', '', NULL, NULL, '[]'::jsonb),
('CAB-0199', 'Granny Items', 25, 'D', 5, 'Pastimes', '', '', '', NULL, NULL, '[]'::jsonb)
on conflict (id) do nothing;
